### PR TITLE
Htsms sim

### PR DESCRIPTION
**Pull request by barentine**
**Proposed changes:**
- add the analysis GUI for linking
- set up the _stopping in httpspooler_v2 (note that I have not read the new implementation in acquisition_backends)
- check that we have an httpspooler in rule_ui

Still to come:
- simulation protocol to turn on/off the laser

Could use a hand from @David-Baddeley if you have a minute:
- I never got the localization settings fold out in the rule page to work properly. At the moment you have to go to the `page`, where you'll initially see nothing, and click the top to expand it down. Then you'll see the arrow you can expand to see settings, but it doesn't re-size so you can actually view anything unless you click the top bar again to make it disappear, then click it again to open it with that folding bit now expanded. Was never an issue for me because I just had my localization settings pre-loaded as a default for my SMLM protocols in my init script.

### CODE REVIEW

**Comment by David-Baddeley** [comment]
Re localisation settings - is there any reason for this to be a folding page? I think it's getting confused as the window doesn't get a size before it's displayed.

**Comment by David-Baddeley** [comment]
@barentine - fixed with dramatically simplified localisation tab. There are a couple of additional things here I'd really like to change to make the UI interaction less spaghetti like (specifically bringing the localisation and recipe tabs inside the 'ChainedAnalysis' tab. Will see if I can get it done quickly ...

**Comment by barentine** [comment]
@David-Baddeley definitely some spaghetti action there! Let me know if it goes smoothly or not.  Thanks for fixing the localization tab.

**Comment by David-Baddeley** [comment]
@barentine with latest push ...
image
image

Editors only show up if you hit "add localisation" or "add Recipe" and then go away again after you click 'Add to chained analysis'. Much happier showing it this way in a walkthrough ;)

**Comment by David-Baddeley** [comment]
@barentine - I'm also going to swap the order of "Add recipe" and "Add localisation".

There's still plenty of spaghetti on the back end, and it would be really nice to make things editable and/or show a bit more info in the blocks, but think this is probably enough for a simple walkthrough.

**Pull request merged**
